USE [PRD]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_Update_newFotos]
	@Cedula VARCHAR(25) = NULL,
	@NewFoto IMAGE = NULL
AS
SET NOCOUNT ON;
BEGIN
	BEGIN TRY
		BEGIN
			IF @Cedula IS NOT NULL AND @NewFoto IS NOT NULL
				BEGIN
					UPDATE [dbo].[Alumnos] SET Foto = @NewFoto WHERE Cedula = @Cedula;
					SELECT TOP 1 IdAl FROM Alumnos WHERE Cedula = @Cedula;
				END
		END
	END TRY
		BEGIN CATCH
			SELECT ERROR_MESSAGE() AS ERROR,
				ERROR_NUMBER() AS ERROR_NRO
		END CATCH;
END